[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = ['python']

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ['toml']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown','mkd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'coil398/vim-go'
on_ft = 'go'
hook_source = 'call config#vim_go#hook_source()'
